# Generated by Django 5.2.6 on 2026-03-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, default='https://i.imgur.com/placeholder.png'),
            preserve_default=False,
        ),
    ]
