# Generated by Django 5.2.6 on 2025-09-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web', 'Web Development'), ('Android', 'Android  Development')], default='Web', max_length=50),
        ),
    ]
